# Generated by Django 2.1.7 on 2019-05-01 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled_article', max_length=30)),
                ('subTitle', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('type_id', models.IntegerField(default=1)),
                ('dir', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ForumGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('couleur', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ForumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=300)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('groupe', models.ManyToManyField(to='monApp.ForumGroup')),
            ],
        ),
        migrations.CreateModel(
            name='LangueSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=50)),
                ('nom_apparent', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='logo')),
            ],
        ),
        migrations.AddField(
            model_name='forumgroup',
            name='logo',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.SET_NULL, to='monApp.logo'),
        ),
    ]
