# Generated by Django 2.1.7 on 2019-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languesection',
            name='groupes',
            field=models.ManyToManyField(to='monApp.ForumGroup'),
        ),
    ]
