# Generated by Django 2.1.7 on 2019-05-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_languesection_groupes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monApp.ArticleType'),
        ),
    ]
