# Generated by Django 2.1.7 on 2019-05-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_auto_20190502_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='img',
            field=models.ImageField(upload_to='monApp/static/img/logo'),
        ),
    ]
