# Generated by Django 2.1.7 on 2019-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0004_auto_20190502_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='langue',
            field=models.ManyToManyField(to='monApp.LangueSection'),
        ),
        migrations.AlterField(
            model_name='languesection',
            name='nom_apparent',
            field=models.CharField(max_length=50),
        ),
    ]
