# Generated by Django 2.1.7 on 2019-05-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_auto_20190525_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletype',
            name='img',
            field=models.ImageField(null=True, upload_to='monApp/static/img/article_icon'),
        ),
    ]
