# Generated by Django 2.2.3 on 2019-09-18 20:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0007_auto_20190525_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('template_txt', models.FilePathField()),
                ('template_html', models.FilePathField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='forumgroup',
            name='mail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='forumuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 18, 20, 3, 35, 886680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='monApp.ArticleType'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img/article_icon'),
        ),
        migrations.AlterField(
            model_name='forumgroup',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='monApp.logo'),
        ),
        migrations.AlterField(
            model_name='forumuser',
            name='identifiant',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='logo',
            name='img',
            field=models.ImageField(upload_to='static/img/logo'),
        ),
        migrations.CreateModel(
            name='PlannedMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, null=True)),
                ('args', models.TextField(null=True)),
                ('sent', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=datetime.datetime(2019, 9, 18, 21, 0))),
                ('mailModel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='monApp.MailModel')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.ForumGroup')),
            ],
        ),
    ]
